[tool.poetry]
name = "web-development"
version = "0.1.0"
description = ""
authors = ["Jhoeel <lunajhoeel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
reflex = "^0.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
